### ISSUE TITLE
firefox(nightly): does not display warning message

### ISSUE THREAD

**Issue by kimyvgy** [sun-asterisk-research/prodwarn#6]
The warning message does not display when accessing production sites.

- Firefox Nightly
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:79.0) Gecko/20100101 Firefox/79.0

**Comment by kimyvgy** [comment]
I'm investigating

**Comment by tranxuanthang** [comment]
This line probably has no value:
```javascript
// src/background.ts
chrome.runtime.onRestartRequired.addListener(migrateDB)
```
It is only for Chrome OS kiosk apps, and throws an error on Firefox. Only `chrome.runtime.onInstalled` is enough since it is already fired when extension is installed, updated, and browser is updated.

Also, in main content script:
https://github.com/sun-asterisk-research/prodwarn/blob/master/src/content-scripts/main.ts#L14
It seems like the message will not be sent when attach Location object (`window.location`) directly. But `window.location.toString()` and `window.location.hostname` works.
